<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-R253MJV" failures="2" tests="3" name="Default test(failed)" time="31.636" errors="0" timestamp="2022-11-04T23:09:14 IST">
  <testcase classname="TestCases.FailedTest" name="varifybotlogoTest" time="0.047">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.varifybotlogoTest(FailedTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- varifybotlogoTest -->
  <testcase classname="TestCases.FailedTest" name="varifyTitleTest" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [1Swag Labs] but found [Swag Labs]">
      <![CDATA[java.lang.AssertionError: expected [1Swag Labs] but found [Swag Labs]
at TestCases.FailedTest.varifyTitleTest(FailedTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- varifyTitleTest -->
  <testcase classname="TestCases.FailedTest" name="varifySwagLabLogoTest" time="0.035"/>
  <testcase classname="TestCases.FailedTest" name="loginToApp1Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp1Test -->
  <testcase classname="TestCases.FailedTest" name="loginToApp2Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp2Test -->
  <testcase classname="TestCases.FailedTest" name="VarifyUrlTest" time="0.0">
    <ignored/>
  </testcase> <!-- VarifyUrlTest -->
</testsuite> <!-- Default test(failed) -->
